name: EB CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install

      - name: Build App
        run: yarn run nx build api --prod --skip-nx-cache

      - name: Generate deployment package
        uses: papeloto/action-zip@v1
        with:
          files: dist/apps/api
          dest: deploy.zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        env:
          VERSION_LABEL: myorgapi-${{ github.run_id }}
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: myorgapi
          environment_name: myorgapi-env
          version_label: ${{ env.VERSION_LABEL }}
          region: us-east-2
          deployment_package: deploy.zip
